### ISSUE TITLE
Make Db constructor compatible with PDO constructor

### ISSUE THREAD

**Issue by v-dem** [v-dem/queasy-db#31]

**Comment by Compolomus** [comment]
Gj

**Comment by Compolomus** [comment]
Ты пробовал другие тестилки?

**Comment by v-dem** [comment]
В смысле?

**Comment by v-dem** [comment]
Кстати сегодня на проблему нарвался. Простой код, который сам по себе работает и вручную проверен, в phpunit виснет наглухо, хотя никакой особой магии внутри нет.

**Comment by v-dem** [comment]
`    public function testRunSelect()
    {
        $db = new Db(['connection' => ['path' => 'tests/resources/test.sqlite']]);

        $statement = $db->run('
            SELECT  count(*)
            FROM    `user_roles`');
    }
`

**Comment by Compolomus** [comment]
Я ещё месяц назад кидал ссылки

**Comment by Compolomus** [comment]
Ну а баги надо тестами покрывать

**Comment by v-dem** [comment]
Баг где-то в phpunit. Код рабочий, я добавил логгер и в тесте он делает вывод в самом конце тестового метода. Из tearDown убрал всё, остальные тесты закомментил. И зависает, причем именно на этом тесте.

**Comment by v-dem** [comment]
Т.е. уже после выхода из теста где-то виснет.

**Comment by v-dem** [comment]
$db->run() это фактически обертка для $pdo->prepare().. bindValue().. execute(), ну и как я говорил после этого вызова логгер в журнал пишет, больше в тестовом методе ничего нет, и... всё, висит.

**Comment by Compolomus** [comment]
Вечером гляну

**Comment by v-dem** [comment]
Так уже разобрался. Кеширование Statement мешало (так-то оно работает, но в PHPUnit нет), это вообще сомнительная идея была. Я наверное сам класс Statement уберу, по крайней мере не вижу как можно с достаточной пользой расширить PDOStatement

**Comment by Compolomus** [comment]
Можно не биндить, а закидывать в execute все забиндится как строки

**Comment by Compolomus** [comment]
https://scrutinizer-ci.com/
https://codeclimate.com/
Бэйджики можешь у меня в репах глянуть

**Comment by Compolomus** [comment]
Видал какую хрень замутил https://github.com/Compolomus/IniObject

**Comment by v-dem** [comment]
Без примеров сложно заценить.
А бейджики пусть пока как есть будут, мне сейчас главное тесты для db, ну и еще кое-какую функциональность добавить, и переходить к собственно фреймворку поскорее.

**Comment by v-dem** [comment]
Readme бы минимальный

**Comment by Compolomus** [comment]
Ну сделай папку doc в неё положи примеры в мд файл и ссылку на него в основном ридми

**Comment by v-dem** [comment]
Да я про твой IniObject :)

**Comment by Compolomus** [comment]
Я его ещё сам не тестил гг, написал, может он вообще не работает, там сохранение в файл прикольное
